
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 25 2026 09:52:12 IST (Aug 25 2026 04:22:12 UTC)

// Verification Directory fv/dut 

module dut(clk, rst, display_data, brightness, row, col, SE, scan_in,
     scan_out);
  input clk, rst, SE, scan_in;
  input [63:0] display_data;
  input [3:0] brightness;
  output [7:0] row, col;
  output scan_out;
  wire clk, rst, SE, scan_in;
  wire [63:0] display_data;
  wire [3:0] brightness;
  wire [7:0] row, col;
  wire scan_out;
  wire [2:0] scan_count;
  wire [3:0] pwm_count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_15, n_16;
  wire n_18, n_19, n_22, n_23, n_24, n_26, n_27, n_30;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  NAND4XL g2102__2398(.A (n_32), .B (n_53), .C (n_40), .D (n_60), .Y
       (col[5]));
  NAND4XL g2100__5107(.A (n_37), .B (n_63), .C (n_49), .D (n_69), .Y
       (col[6]));
  NAND4XL g2101__6260(.A (n_34), .B (n_59), .C (n_46), .D (n_64), .Y
       (col[7]));
  NAND4XL g2103__4319(.A (n_35), .B (n_58), .C (n_42), .D (n_56), .Y
       (col[4]));
  NAND4XL g2104__8428(.A (n_36), .B (n_67), .C (n_44), .D (n_51), .Y
       (col[1]));
  NAND4XL g2105__5526(.A (n_33), .B (n_57), .C (n_41), .D (n_66), .Y
       (col[2]));
  NAND4XL g2099__6783(.A (n_39), .B (n_52), .C (n_45), .D (n_55), .Y
       (col[3]));
  NAND4XL g2106__3680(.A (n_30), .B (n_54), .C (n_50), .D (n_70), .Y
       (col[0]));
  AOI22XL g2124__1617(.A0 (display_data[48]), .A1 (n_68), .B0
       (display_data[40]), .B1 (n_47), .Y (n_70));
  AOI22XL g2109__2802(.A0 (display_data[22]), .A1 (n_65), .B0
       (display_data[54]), .B1 (n_68), .Y (n_69));
  AOI22XL g2123__1705(.A0 (display_data[1]), .A1 (n_62), .B0
       (display_data[25]), .B1 (n_38), .Y (n_67));
  AOI22XL g2115__5122(.A0 (display_data[18]), .A1 (n_65), .B0
       (display_data[50]), .B1 (n_68), .Y (n_66));
  AOI22XL g2108__8246(.A0 (display_data[55]), .A1 (n_68), .B0
       (display_data[63]), .B1 (n_61), .Y (n_64));
  AOI22XL g2116__7098(.A0 (display_data[6]), .A1 (n_62), .B0
       (display_data[62]), .B1 (n_61), .Y (n_63));
  AOI22XL g2125__6131(.A0 (display_data[53]), .A1 (n_68), .B0
       (display_data[61]), .B1 (n_61), .Y (n_60));
  AOI22XL g2127__1881(.A0 (display_data[7]), .A1 (n_62), .B0
       (display_data[23]), .B1 (n_65), .Y (n_59));
  AOI22XL g2113__5115(.A0 (display_data[4]), .A1 (n_62), .B0
       (display_data[20]), .B1 (n_65), .Y (n_58));
  AOI22XL g2118__7482(.A0 (display_data[2]), .A1 (n_62), .B0
       (display_data[58]), .B1 (n_61), .Y (n_57));
  AOI22XL g2129__4733(.A0 (display_data[52]), .A1 (n_68), .B0
       (display_data[60]), .B1 (n_61), .Y (n_56));
  AOI22XL g2110__6161(.A0 (display_data[51]), .A1 (n_68), .B0
       (display_data[59]), .B1 (n_61), .Y (n_55));
  AOI22XL g2128__9315(.A0 (display_data[0]), .A1 (n_62), .B0
       (display_data[16]), .B1 (n_65), .Y (n_54));
  AOI22XL g2119__9945(.A0 (display_data[5]), .A1 (n_62), .B0
       (display_data[21]), .B1 (n_65), .Y (n_53));
  AOI22XL g2114__2883(.A0 (display_data[3]), .A1 (n_62), .B0
       (display_data[19]), .B1 (n_65), .Y (n_52));
  AOI22XL g2121__2346(.A0 (display_data[17]), .A1 (n_65), .B0
       (display_data[49]), .B1 (n_68), .Y (n_51));
  AOI22XL g2126__1666(.A0 (display_data[32]), .A1 (n_48), .B0
       (display_data[8]), .B1 (n_43), .Y (n_50));
  AOI22XL g2107__7410(.A0 (display_data[38]), .A1 (n_48), .B0
       (display_data[46]), .B1 (n_47), .Y (n_49));
  AOI22XL g2111__6417(.A0 (display_data[39]), .A1 (n_48), .B0
       (display_data[47]), .B1 (n_47), .Y (n_46));
  AOI22XL g2112__5477(.A0 (display_data[35]), .A1 (n_48), .B0
       (display_data[43]), .B1 (n_47), .Y (n_45));
  AOI22XL g2120__2398(.A0 (display_data[33]), .A1 (n_48), .B0
       (display_data[9]), .B1 (n_43), .Y (n_44));
  AOI22XL g2130__5107(.A0 (display_data[36]), .A1 (n_48), .B0
       (display_data[44]), .B1 (n_47), .Y (n_42));
  AOI22XL g2117__6260(.A0 (display_data[34]), .A1 (n_48), .B0
       (display_data[42]), .B1 (n_47), .Y (n_41));
  AOI22XL g2122__4319(.A0 (display_data[37]), .A1 (n_48), .B0
       (display_data[45]), .B1 (n_47), .Y (n_40));
  SDFFQX1 \pwm_count_reg[3] (.CK (clk), .D (n_27), .SI (scan_count[2]),
       .SE (SE), .Q (pwm_count[3]));
  AOI22XL g2132__8428(.A0 (display_data[11]), .A1 (n_43), .B0
       (display_data[27]), .B1 (n_38), .Y (n_39));
  AOI22XL g2131__5526(.A0 (display_data[14]), .A1 (n_43), .B0
       (display_data[30]), .B1 (n_38), .Y (n_37));
  AOI22XL g2137__6783(.A0 (display_data[41]), .A1 (n_47), .B0
       (display_data[57]), .B1 (n_61), .Y (n_36));
  AOI22XL g2133__3680(.A0 (display_data[12]), .A1 (n_43), .B0
       (display_data[28]), .B1 (n_38), .Y (n_35));
  AOI22XL g2136__1617(.A0 (display_data[15]), .A1 (n_43), .B0
       (display_data[31]), .B1 (n_38), .Y (n_34));
  AOI22XL g2134__2802(.A0 (display_data[10]), .A1 (n_43), .B0
       (display_data[26]), .B1 (n_38), .Y (n_33));
  AOI22XL g2138__1705(.A0 (display_data[13]), .A1 (n_43), .B0
       (display_data[29]), .B1 (n_38), .Y (n_32));
  SDFFQX1 \pwm_count_reg[2] (.CK (clk), .D (n_18), .SI (scan_in), .SE
       (SE), .Q (scan_count[2]));
  NOR2BX1 g2141__5122(.AN (row[0]), .B (n_26), .Y (n_62));
  AOI22XL g2135__8246(.A0 (display_data[24]), .A1 (n_38), .B0
       (display_data[56]), .B1 (n_61), .Y (n_30));
  AND2X1 g2142__7098(.A (row[6]), .B (n_23), .Y (n_68));
  OA21X1 g2143__6131(.A0 (n_11), .A1 (n_19), .B0 (row[4]), .Y (n_48));
  NOR2X1 g2144__1881(.A (rst), .B (n_15), .Y (n_27));
  AOI21XL g2148__5115(.A0 (brightness[0]), .A1 (n_7), .B0 (n_24), .Y
       (n_26));
  AND2X1 g2146__7482(.A (row[1]), .B (n_24), .Y (n_43));
  OAI2BB1X1 g2149__4733(.A0N (brightness[2]), .A1N (n_22), .B0 (n_13),
       .Y (n_23));
  SDFFQX1 \scan_count_reg[1] (.CK (clk), .D (n_8), .SI (scan_count[0]),
       .SE (SE), .Q (scan_out));
  OA21X1 g2151__6161(.A0 (n_22), .A1 (n_16), .B0 (row[2]), .Y (n_65));
  AND2X1 g2150__9315(.A (row[5]), .B (n_19), .Y (n_47));
  NOR2X1 g2145__9945(.A (rst), .B (n_9), .Y (n_18));
  AND2X1 g2147__2883(.A (row[3]), .B (n_16), .Y (n_38));
  XNOR2X1 g2154__2346(.A (pwm_count[3]), .B (row[7]), .Y (n_15));
  OAI21XL g2155__1666(.A0 (n_0), .A1 (n_12), .B0 (n_13), .Y (n_19));
  NAND3XL g2152__7410(.A (n_13), .B (n_10), .C (n_12), .Y (n_24));
  NOR2BX1 g2156__6417(.AN (brightness[0]), .B (n_12), .Y (n_11));
  NOR2BX1 g2157__5477(.AN (brightness[0]), .B (n_10), .Y (n_22));
  SDFFQX1 \scan_count_reg[0] (.CK (clk), .D (n_1), .SI (pwm_count[3]),
       .SE (SE), .Q (scan_count[0]));
  AOI21X1 g2160__2398(.A0 (scan_count[2]), .A1 (n_4), .B0 (row[3]), .Y
       (n_9));
  NAND2XL g2158__5107(.A (n_13), .B (n_12), .Y (n_16));
  NOR2BX1 g2161__6260(.AN (row[7]), .B (n_13), .Y (n_61));
  AOI21XL g2159__4319(.A0 (n_3), .A1 (n_6), .B0 (rst), .Y (n_8));
  NAND2XL g2163__8428(.A (brightness[1]), .B (n_7), .Y (n_10));
  AND2X1 g2162__5526(.A (n_2), .B (scan_count[2]), .Y (row[4]));
  NOR2XL g2167__6783(.A (n_5), .B (n_6), .Y (row[5]));
  NOR2X1 g2165__3680(.A (n_5), .B (n_4), .Y (row[7]));
  NOR2X1 g2164__1617(.A (scan_count[2]), .B (n_4), .Y (row[3]));
  NOR2XL g2170__2802(.A (n_5), .B (n_3), .Y (row[6]));
  AND2X1 g2169__1705(.A (n_2), .B (n_5), .Y (row[0]));
  NOR2XL g2168__5122(.A (scan_count[2]), .B (n_6), .Y (row[1]));
  NOR2XL g2171__8246(.A (scan_count[2]), .B (n_3), .Y (row[2]));
  NAND2XL g2172__7098(.A (brightness[2]), .B (n_7), .Y (n_12));
  NOR2X1 g2173__6131(.A (rst), .B (scan_count[0]), .Y (n_1));
  NAND2BXL g2175__1881(.AN (brightness[3]), .B (pwm_count[3]), .Y
       (n_7));
  NAND2BX1 g2174__5115(.AN (scan_out), .B (scan_count[0]), .Y (n_6));
  NOR2XL g2176__7482(.A (scan_count[0]), .B (scan_out), .Y (n_2));
  NAND2BX1 g2178__4733(.AN (scan_count[0]), .B (scan_out), .Y (n_3));
  NAND2X1 g2177__6161(.A (scan_out), .B (scan_count[0]), .Y (n_4));
  NAND2BXL g2179__9315(.AN (pwm_count[3]), .B (brightness[3]), .Y
       (n_13));
  INVXL g2180(.A (brightness[1]), .Y (n_0));
  INVX1 g2181(.A (scan_count[2]), .Y (n_5));
// INPUTS
PADDI c(.PAD(clk), .Y(clk));
PADDI r(.PAD(rst), .Y(rst));

PADDI dd0(.PAD(display_data[0]),  .Y(display_data[0]));
PADDI dd1(.PAD(display_data[1]),  .Y(display_data[1]));
PADDI dd2(.PAD(display_data[2]),  .Y(display_data[2]));
PADDI dd3(.PAD(display_data[3]),  .Y(display_data[3]));
PADDI dd4(.PAD(display_data[4]),  .Y(display_data[4]));
PADDI dd5(.PAD(display_data[5]),  .Y(display_data[5]));
PADDI dd6(.PAD(display_data[6]),  .Y(display_data[6]));
PADDI dd7(.PAD(display_data[7]),  .Y(display_data[7]));

PADDI dd8(.PAD(display_data[8]),  .Y(display_data[8]));
PADDI dd9(.PAD(display_data[9]),  .Y(display_data[9]));
PADDI dd10(.PAD(display_data[10]), .Y(display_data[10]));
PADDI dd11(.PAD(display_data[11]), .Y(display_data[11]));
PADDI dd12(.PAD(display_data[12]), .Y(display_data[12]));
PADDI dd13(.PAD(display_data[13]), .Y(display_data[13]));
PADDI dd14(.PAD(display_data[14]), .Y(display_data[14]));
PADDI dd15(.PAD(display_data[15]), .Y(display_data[15]));

PADDI dd16(.PAD(display_data[16]), .Y(display_data[16]));
PADDI dd17(.PAD(display_data[17]), .Y(display_data[17]));
PADDI dd18(.PAD(display_data[18]), .Y(display_data[18]));
PADDI dd19(.PAD(display_data[19]), .Y(display_data[19]));
PADDI dd20(.PAD(display_data[20]), .Y(display_data[20]));
PADDI dd21(.PAD(display_data[21]), .Y(display_data[21]));
PADDI dd22(.PAD(display_data[22]), .Y(display_data[22]));
PADDI dd23(.PAD(display_data[23]), .Y(display_data[23]));

PADDI dd24(.PAD(display_data[24]), .Y(display_data[24]));
PADDI dd25(.PAD(display_data[25]), .Y(display_data[25]));
PADDI dd26(.PAD(display_data[26]), .Y(display_data[26]));
PADDI dd27(.PAD(display_data[27]), .Y(display_data[27]));
PADDI dd28(.PAD(display_data[28]), .Y(display_data[28]));
PADDI dd29(.PAD(display_data[29]), .Y(display_data[29]));
PADDI dd30(.PAD(display_data[30]), .Y(display_data[30]));
PADDI dd31(.PAD(display_data[31]), .Y(display_data[31]));

PADDI dd32(.PAD(display_data[32]), .Y(display_data[32]));
PADDI dd33(.PAD(display_data[33]), .Y(display_data[33]));
PADDI dd34(.PAD(display_data[34]), .Y(display_data[34]));
PADDI dd35(.PAD(display_data[35]), .Y(display_data[35]));
PADDI dd36(.PAD(display_data[36]), .Y(display_data[36]));
PADDI dd37(.PAD(display_data[37]), .Y(display_data[37]));
PADDI dd38(.PAD(display_data[38]), .Y(display_data[38]));
PADDI dd39(.PAD(display_data[39]), .Y(display_data[39]));

PADDI dd40(.PAD(display_data[40]), .Y(display_data[40]));
PADDI dd41(.PAD(display_data[41]), .Y(display_data[41]));
PADDI dd42(.PAD(display_data[42]), .Y(display_data[42]));
PADDI dd43(.PAD(display_data[43]), .Y(display_data[43]));
PADDI dd44(.PAD(display_data[44]), .Y(display_data[44]));
PADDI dd45(.PAD(display_data[45]), .Y(display_data[45]));
PADDI dd46(.PAD(display_data[46]), .Y(display_data[46]));
PADDI dd47(.PAD(display_data[47]), .Y(display_data[47]));

PADDI dd48(.PAD(display_data[48]), .Y(display_data[48]));
PADDI dd49(.PAD(display_data[49]), .Y(display_data[49]));
PADDI dd50(.PAD(display_data[50]), .Y(display_data[50]));
PADDI dd51(.PAD(display_data[51]), .Y(display_data[51]));
PADDI dd52(.PAD(display_data[52]), .Y(display_data[52]));
PADDI dd53(.PAD(display_data[53]), .Y(display_data[53]));
PADDI dd54(.PAD(display_data[54]), .Y(display_data[54]));
PADDI dd55(.PAD(display_data[55]), .Y(display_data[55]));

PADDI dd56(.PAD(display_data[56]), .Y(display_data[56]));
PADDI dd57(.PAD(display_data[57]), .Y(display_data[57]));
PADDI dd58(.PAD(display_data[58]), .Y(display_data[58]));
PADDI dd59(.PAD(display_data[59]), .Y(display_data[59]));
PADDI dd60(.PAD(display_data[60]), .Y(display_data[60]));
PADDI dd61(.PAD(display_data[61]), .Y(display_data[61]));
PADDI dd62(.PAD(display_data[62]), .Y(display_data[62]));
PADDI dd63(.PAD(display_data[63]), .Y(display_data[63]));

PADDI b0(.PAD(brightness[0]), .Y(brightness[0]));
PADDI b1(.PAD(brightness[1]), .Y(brightness[1]));
PADDI b2(.PAD(brightness[2]), .Y(brightness[2]));
PADDI b3(.PAD(brightness[3]), .Y(brightness[3]));

PADDI se(.PAD(SE), .Y(SE));
PADDI si(.PAD(scan_in), .Y(scan_in));


// OUTPUTS
PADDO row0(.A(row[0]), .PAD(row[0]));
PADDO row1(.A(row[1]), .PAD(row[1]));
PADDO row2(.A(row[2]), .PAD(row[2]));
PADDO row3(.A(row[3]), .PAD(row[3]));
PADDO row4(.A(row[4]), .PAD(row[4]));
PADDO row5(.A(row[5]), .PAD(row[5]));
PADDO row6(.A(row[6]), .PAD(row[6]));
PADDO row7(.A(row[7]), .PAD(row[7]));

PADDO col0(.A(col[0]), .PAD(col[0]));
PADDO col1(.A(col[1]), .PAD(col[1]));
PADDO col2(.A(col[2]), .PAD(col[2]));
PADDO col3(.A(col[3]), .PAD(col[3]));
PADDO col4(.A(col[4]), .PAD(col[4]));
PADDO col5(.A(col[5]), .PAD(col[5]));
PADDO col6(.A(col[6]), .PAD(col[6]));
PADDO col7(.A(col[7]), .PAD(col[7]));

PADDO so(.A(scan_out), .PAD(scan_out));
endmodule

