
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 25 2026 13:54:57 IST (Aug 25 2026 08:24:57 UTC)

// Verification Directory fv/dut 

module dut(clk, rst, display_data, brightness, refresh_div, row, col);
  input clk, rst;
  input [63:0] display_data;
  input [3:0] brightness;
  input [15:0] refresh_div;
  output [7:0] row, col;
  wire clk, rst;
  wire [63:0] display_data;
  wire [3:0] brightness;
  wire [15:0] refresh_div;
  wire [7:0] row, col;
  wire [6:0] scan_pwm_counter;
  wire [15:0] refresh_counter;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_16, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_27, n_30, n_31, n_32, n_33, n_34;
  wire n_36, n_43, n_46, n_47, n_48, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_68, n_71, n_72, n_76;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_87, n_91;
  wire n_92, n_93, n_98, n_99, n_103, n_105, n_108, n_111;
  wire n_112, n_113, n_114, n_118, n_119, n_121, n_122, n_125;
  wire n_127, n_130, n_132, n_134, n_135, n_136, n_137, n_142;
  wire n_143, n_144, n_145, n_147, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_163, n_164, n_165, n_166, n_167, n_170;
  wire n_171, n_172, n_173, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201, n_202, n_203, n_204;
  wire n_212, n_224, n_230, n_231, n_233, n_234, n_235, n_236;
  wire n_242, n_247, n_256, n_257, n_282, n_372, n_374, n_375;
  wire n_381, n_387, n_389, n_396, n_399, n_401, n_407, n_431;
  wire n_517, n_542, n_563, n_574, n_576, n_577, n_580, n_636;
  wire n_673, n_704, n_707, n_709, n_712, n_716, n_723, n_724;
  wire n_730, n_733, n_737, n_740, n_741, n_742, n_743, n_744;
  wire n_750, n_751, n_752, n_754, n_755, n_756, n_757, n_758;
  wire n_759, n_760, n_762, n_769, n_771, n_772, n_774, n_791;
  wire n_795, n_796, n_797, n_802, n_803, n_807, n_809, n_811;
  wire n_815, n_857, n_858, n_859, n_860, n_861, n_862, n_863;
  wire n_896, n_897, n_898, n_899, n_900, n_901, n_902, n_903;
  wire n_904, n_906, n_907, n_908, n_910, n_911, n_912, n_913;
  wire n_914, n_915, n_916, n_917, n_918, n_933, n_936, n_966;
  wire n_968, n_974, n_975, n_976, n_977, n_978, n_979, n_980;
  wire n_982, n_986, n_987, n_988, n_989, n_990, n_991, n_992;
  wire n_993, n_995, n_996, n_997, n_998, n_999, n_1000, n_1002;
  wire n_1004, n_1005, n_1006, n_1011, n_1012, n_1013, n_1014, n_1015;
  wire n_1038, n_1040, n_1041, n_1042, n_1045, n_1046, n_1047, n_1048;
  wire n_1049, n_1050, n_1051;
  DFFRHQX1 \scan_pwm_counter_reg[0] (.RN (n_282), .CK (clk), .D
       (n_1005), .Q (scan_pwm_counter[0]));
  DFFRHQX1 \refresh_counter_reg[11] (.RN (n_282), .CK (clk), .D
       (n_974), .Q (refresh_counter[11]));
  DFFRHQX1 \refresh_counter_reg[0] (.RN (n_282), .CK (clk), .D (n_431),
       .Q (refresh_counter[0]));
  DFFRHQX1 \refresh_counter_reg[3] (.RN (n_282), .CK (clk), .D (n_542),
       .Q (refresh_counter[3]));
  DFFRHQX1 \refresh_counter_reg[2] (.RN (n_282), .CK (clk), .D (n_860),
       .Q (refresh_counter[2]));
  SDFFRHQX1 \scan_pwm_counter_reg[1] (.RN (n_282), .CK (clk), .D
       (scan_pwm_counter[1]), .SI (n_20), .SE (n_979), .Q
       (scan_pwm_counter[1]));
  DFFRHQX1 \refresh_counter_reg[1] (.RN (n_282), .CK (clk), .D (n_407),
       .Q (refresh_counter[1]));
  DFFRHQX1 \refresh_counter_reg[13] (.RN (n_282), .CK (clk), .D
       (n_802), .Q (refresh_counter[13]));
  SDFFRHQX1 \scan_pwm_counter_reg[5] (.RN (n_282), .CK (clk), .D
       (scan_pwm_counter[5]), .SI (n_87), .SE (n_979), .Q
       (scan_pwm_counter[5]));
  SDFFRHQX1 \scan_pwm_counter_reg[3] (.RN (n_282), .CK (clk), .D
       (scan_pwm_counter[3]), .SI (n_63), .SE (n_979), .Q
       (scan_pwm_counter[3]));
  SDFFRHQX1 \scan_pwm_counter_reg[4] (.RN (n_282), .CK (clk), .D
       (scan_pwm_counter[4]), .SI (n_72), .SE (n_979), .Q
       (scan_pwm_counter[4]));
  DFFRHQX1 \refresh_counter_reg[10] (.RN (n_282), .CK (clk), .D
       (n_809), .Q (refresh_counter[10]));
  SDFFRHQX1 \scan_pwm_counter_reg[6] (.RN (n_282), .CK (clk), .D
       (scan_pwm_counter[6]), .SI (n_119), .SE (n_979), .Q
       (scan_pwm_counter[6]));
  DFFRHQX1 \refresh_counter_reg[14] (.RN (n_282), .CK (clk), .D
       (n_980), .Q (refresh_counter[14]));
  DFFRHQX1 \refresh_counter_reg[8] (.RN (n_282), .CK (clk), .D (n_862),
       .Q (refresh_counter[8]));
  DFFRHQX1 \refresh_counter_reg[15] (.RN (n_282), .CK (clk), .D
       (n_996), .Q (refresh_counter[15]));
  DFFRHQX1 \refresh_counter_reg[5] (.RN (n_282), .CK (clk), .D (n_858),
       .Q (refresh_counter[5]));
  DFFRHQX1 \refresh_counter_reg[9] (.RN (n_282), .CK (clk), .D (n_861),
       .Q (refresh_counter[9]));
  DFFRHQX1 \refresh_counter_reg[4] (.RN (n_282), .CK (clk), .D (n_807),
       .Q (refresh_counter[4]));
  DFFRHQX1 \refresh_counter_reg[12] (.RN (n_282), .CK (clk), .D
       (n_563), .Q (refresh_counter[12]));
  DFFRHQX1 \refresh_counter_reg[7] (.RN (n_282), .CK (clk), .D (n_906),
       .Q (refresh_counter[7]));
  DFFRHQX1 \refresh_counter_reg[6] (.RN (n_282), .CK (clk), .D (n_863),
       .Q (refresh_counter[6]));
  NOR2X1 g7848__2346(.A (n_372), .B (n_1014), .Y (n_256));
  NAND2X2 g7859__8428(.A (n_236), .B (n_740), .Y (n_247));
  NOR2XL g7862__5526(.A (n_933), .B (n_234), .Y (n_242));
  NOR2BX1 g7868__1705(.AN (n_224), .B (n_231), .Y (n_236));
  INVXL g7871(.A (n_918), .Y (n_235));
  NAND2XL g7864__5122(.A (n_167), .B (n_903), .Y (n_234));
  NAND2X1 g7869__8246(.A (n_903), .B (n_743), .Y (n_233));
  AOI2BB1XL g7872__1881(.A0N (refresh_counter[15]), .A1N (n_230), .B0
       (n_212), .Y (n_231));
  NAND4XL g7882__5115(.A (n_202), .B (n_189), .C (n_192), .D (n_195),
       .Y (col[2]));
  NAND4XL g7881__7482(.A (n_184), .B (n_186), .C (n_160), .D (n_198),
       .Y (col[6]));
  NAND4XL g7884__4733(.A (n_171), .B (n_164), .C (n_179), .D (n_182),
       .Y (col[5]));
  NAND4XL g7886__6161(.A (n_185), .B (n_170), .C (n_166), .D (n_156),
       .Y (col[4]));
  NAND4XL g7888__9315(.A (n_180), .B (n_163), .C (n_159), .D (n_200),
       .Y (col[3]));
  AOI21XL g7874__9945(.A0 (refresh_counter[15]), .A1 (n_230), .B0
       (n_78), .Y (n_224));
  NAND4XL g7873__2883(.A (n_158), .B (n_157), .C (n_176), .D (n_201),
       .Y (col[7]));
  NAND4XL g7885__1666(.A (n_172), .B (n_173), .C (n_177), .D (n_178),
       .Y (col[0]));
  NAND4XL g7883__5107(.A (n_181), .B (n_199), .C (n_165), .D (n_183),
       .Y (col[1]));
  NAND2XL g7901__4319(.A (refresh_counter[14]), .B (n_203), .Y (n_212));
  INVXL g7914(.A (n_203), .Y (n_204));
  AOI22XL g7942__2802(.A0 (display_data[2]), .A1 (n_197), .B0
       (display_data[10]), .B1 (n_196), .Y (n_202));
  AOI22XL g7930__1705(.A0 (display_data[55]), .A1 (n_188), .B0
       (display_data[63]), .B1 (n_187), .Y (n_201));
  AOI22XL g7931__5122(.A0 (display_data[19]), .A1 (n_194), .B0
       (display_data[27]), .B1 (n_193), .Y (n_200));
  AOI22XL g7936__8246(.A0 (display_data[33]), .A1 (n_191), .B0
       (display_data[41]), .B1 (n_190), .Y (n_199));
  AOI22XL g7937__7098(.A0 (display_data[6]), .A1 (n_197), .B0
       (display_data[14]), .B1 (n_196), .Y (n_198));
  AOI22XL g7938__6131(.A0 (display_data[18]), .A1 (n_194), .B0
       (display_data[26]), .B1 (n_193), .Y (n_195));
  AOI22XL g7939__1881(.A0 (display_data[34]), .A1 (n_191), .B0
       (display_data[42]), .B1 (n_190), .Y (n_192));
  AOI22XL g7940__5115(.A0 (display_data[50]), .A1 (n_188), .B0
       (display_data[58]), .B1 (n_187), .Y (n_189));
  AOI22XL g7941__7482(.A0 (display_data[54]), .A1 (n_188), .B0
       (display_data[62]), .B1 (n_187), .Y (n_186));
  AOI22XL g7929__4733(.A0 (display_data[20]), .A1 (n_194), .B0
       (display_data[28]), .B1 (n_193), .Y (n_185));
  AOI22XL g7943__6161(.A0 (display_data[22]), .A1 (n_194), .B0
       (display_data[30]), .B1 (n_193), .Y (n_184));
  AOI22XL g7944__9315(.A0 (display_data[17]), .A1 (n_194), .B0
       (display_data[25]), .B1 (n_193), .Y (n_183));
  AOI22XL g7945__9945(.A0 (display_data[21]), .A1 (n_194), .B0
       (display_data[29]), .B1 (n_193), .Y (n_182));
  AOI22XL g7948__2883(.A0 (display_data[1]), .A1 (n_197), .B0
       (display_data[9]), .B1 (n_196), .Y (n_181));
  AOI22XL g7947__2346(.A0 (display_data[3]), .A1 (n_197), .B0
       (display_data[11]), .B1 (n_196), .Y (n_180));
  AOI22XL g7949__1666(.A0 (display_data[53]), .A1 (n_188), .B0
       (display_data[61]), .B1 (n_187), .Y (n_179));
  AOI22XL g7950__7410(.A0 (display_data[48]), .A1 (n_188), .B0
       (display_data[56]), .B1 (n_187), .Y (n_178));
  AOI22XL g7951__6417(.A0 (display_data[16]), .A1 (n_194), .B0
       (display_data[24]), .B1 (n_193), .Y (n_177));
  AOI22XL g7952__5477(.A0 (display_data[23]), .A1 (n_194), .B0
       (display_data[31]), .B1 (n_193), .Y (n_176));
  AOI22XL g7954__5107(.A0 (display_data[32]), .A1 (n_191), .B0
       (display_data[40]), .B1 (n_190), .Y (n_173));
  AOI22XL g7955__6260(.A0 (display_data[0]), .A1 (n_197), .B0
       (display_data[8]), .B1 (n_196), .Y (n_172));
  AOI22XL g7956__4319(.A0 (display_data[5]), .A1 (n_197), .B0
       (display_data[13]), .B1 (n_196), .Y (n_171));
  AOI22XL g7928__8428(.A0 (display_data[36]), .A1 (n_191), .B0
       (display_data[44]), .B1 (n_190), .Y (n_170));
  NOR2XL g7900__6783(.A (n_744), .B (n_1046), .Y (n_167));
  AOI22XL g7927__3680(.A0 (display_data[52]), .A1 (n_188), .B0
       (display_data[60]), .B1 (n_187), .Y (n_166));
  AOI22XL g7946__1617(.A0 (display_data[49]), .A1 (n_188), .B0
       (display_data[57]), .B1 (n_187), .Y (n_165));
  AOI22XL g7953__2802(.A0 (display_data[37]), .A1 (n_191), .B0
       (display_data[45]), .B1 (n_190), .Y (n_164));
  AOI22XL g7915__1705(.A0 (display_data[51]), .A1 (n_188), .B0
       (display_data[59]), .B1 (n_187), .Y (n_163));
  AOI22XL g7918__8246(.A0 (display_data[38]), .A1 (n_191), .B0
       (display_data[46]), .B1 (n_190), .Y (n_160));
  AOI22XL g7921__7098(.A0 (display_data[35]), .A1 (n_191), .B0
       (display_data[43]), .B1 (n_190), .Y (n_159));
  AOI22XL g7924__6131(.A0 (display_data[7]), .A1 (n_197), .B0
       (display_data[15]), .B1 (n_196), .Y (n_158));
  AOI22XL g7925__1881(.A0 (display_data[39]), .A1 (n_191), .B0
       (display_data[47]), .B1 (n_190), .Y (n_157));
  AOI22XL g7926__5115(.A0 (display_data[4]), .A1 (n_197), .B0
       (display_data[12]), .B1 (n_196), .Y (n_156));
  AOI21XL g7963__7482(.A0 (refresh_div[14]), .A1 (n_899), .B0 (n_155),
       .Y (n_203));
  NAND2BX1 g7905__4733(.AN (n_155), .B (refresh_div[15]), .Y (n_230));
  NOR2XL g7976__7410(.A (refresh_div[14]), .B (n_899), .Y (n_155));
  AND2X1 g7979__5107(.A (n_145), .B (n_144), .Y (n_197));
  NOR2BX1 g7980__6260(.AN (n_145), .B (n_143), .Y (n_188));
  NOR2BX1 g7981__4319(.AN (n_144), .B (n_142), .Y (n_196));
  NOR2XL g7982__8428(.A (n_143), .B (n_142), .Y (n_187));
  NOR2BX1 g7983__5526(.AN (n_145), .B (n_134), .Y (n_191));
  AOI21X1 g7920__1617(.A0 (n_127), .A1 (n_760), .B0 (n_759), .Y
       (n_137));
  NAND2XL g7919__2802(.A (refresh_counter[9]), .B (n_132), .Y (n_136));
  AND2X1 g7993__5122(.A (n_145), .B (n_135), .Y (n_194));
  NOR2BX1 g7992__8246(.AN (n_135), .B (n_142), .Y (n_193));
  NOR2XL g7991__7098(.A (n_134), .B (n_142), .Y (n_190));
  NAND2XL g8002__5115(.A (n_114), .B (n_130), .Y (n_147));
  AOI21XL g7971__2883(.A0 (refresh_div[9]), .A1 (n_111), .B0 (n_113),
       .Y (n_132));
  OR2X1 g8004__7410(.A (n_71), .B (n_122), .Y (n_142));
  NOR2XL g7998__6417(.A (scan_pwm_counter[4]), .B (n_122), .Y (n_145));
  AOI22X1 g7967__5477(.A0 (refresh_counter[5]), .A1 (n_103), .B0
       (refresh_counter[4]), .B1 (n_741), .Y (n_121));
  NAND2XL g7891__2398(.A (n_134), .B (n_987), .Y (n_119));
  XOR2XL g7860__5107(.A (n_396), .B (n_704), .Y (n_118));
  NAND2BXL g8005__8428(.AN (n_113), .B (refresh_div[10]), .Y (n_114));
  XOR2XL g7851__5526(.A (refresh_counter[7]), .B (n_92), .Y (n_112));
  NAND2BXL g8006__6783(.AN (refresh_div[10]), .B (n_113), .Y (n_130));
  OAI2BB1X1 g8009__3680(.A0N (refresh_div[8]), .A1N (n_99), .B0
       (n_111), .Y (n_125));
  XOR2XL g7957__8246(.A (n_389), .B (n_81), .Y (n_105));
  OAI2BB1X1 g7988__5115(.A0N (refresh_div[7]), .A1N (n_82), .B0 (n_99),
       .Y (n_127));
  OAI211X1 g8010__7482(.A0 (brightness[3]), .A1 (n_13), .B0 (n_282),
       .C0 (n_79), .Y (n_122));
  XNOR2X1 g7867__4733(.A (n_982), .B (n_91), .Y (n_98));
  XNOR2X1 g7899__9945(.A (refresh_counter[9]), .B (n_1048), .Y (n_93));
  OR2X1 g8012__2883(.A (refresh_div[8]), .B (n_99), .Y (n_111));
  NOR2BX1 g8013__2346(.AN (n_30), .B (n_99), .Y (n_113));
  NAND2X2 g7878__1666(.A (n_982), .B (n_91), .Y (n_92));
  NAND2X1 g7962__5477(.A (n_389), .B (n_914), .Y (n_108));
  XNOR2X1 g7911__2398(.A (scan_pwm_counter[5]), .B (n_76), .Y (n_87));
  AOI21X1 g8001__4319(.A0 (refresh_div[5]), .A1 (n_66), .B0 (n_83), .Y
       (n_103));
  NAND2BXL g8018__5526(.AN (refresh_div[6]), .B (n_83), .Y (n_82));
  INVXL g7973(.A (n_914), .Y (n_81));
  XOR2XL g7910__6783(.A (n_797), .B (n_374), .Y (n_80));
  AOI22XL g8021__3680(.A0 (n_52), .A1 (n_55), .B0 (n_54), .B1
       (scan_pwm_counter[2]), .Y (n_79));
  NOR4X1 g8031__1617(.A (refresh_div[5]), .B (refresh_div[15]), .C
       (refresh_div[14]), .D (n_56), .Y (n_78));
  NAND2XL g8019__2802(.A (n_32), .B (n_83), .Y (n_99));
  NOR2X2 g7935__5122(.A (n_375), .B (n_797), .Y (n_91));
  AOI21X1 g7985__6131(.A0 (n_71), .A1 (n_62), .B0 (n_64), .Y (n_72));
  NOR3XL g8033__7482(.A (refresh_div[4]), .B (refresh_div[5]), .C
       (n_68), .Y (n_83));
  INVXL g8026(.A (n_65), .Y (n_66));
  INVX1 g7996(.A (n_64), .Y (n_76));
  OA21X1 g8016__6161(.A0 (scan_pwm_counter[3]), .A1 (n_517), .B0
       (n_62), .Y (n_63));
  XOR2XL g8014__9315(.A (n_791), .B (n_27), .Y (n_61));
  NOR2X2 g8000__2883(.A (n_71), .B (n_62), .Y (n_64));
  NAND2X1 g8028__7410(.A (n_57), .B (refresh_counter[2]), .Y (n_58));
  OR4X1 g8035__6417(.A (refresh_div[3]), .B (refresh_div[4]), .C
       (n_24), .D (n_33), .Y (n_56));
  AO21X1 g8034__5477(.A0 (n_25), .A1 (scan_pwm_counter[2]), .B0 (n_54),
       .Y (n_55));
  NOR2XL g8029__5107(.A (refresh_div[4]), .B (n_68), .Y (n_65));
  AOI2BB1X1 g8038__6260(.A0N (n_47), .A1N (refresh_counter[1]), .B0
       (n_6), .Y (n_53));
  OAI211X1 g8042__4319(.A0 (brightness[1]), .A1 (n_10), .B0 (n_22), .C0
       (n_43), .Y (n_52));
  NAND2BXL g8046__8428(.AN (n_50), .B (refresh_div[3]), .Y (n_51));
  AOI21XL g8036__5526(.A0 (refresh_div[2]), .A1 (n_12), .B0 (n_50), .Y
       (n_57));
  NAND2X2 g8024__3680(.A (scan_pwm_counter[3]), .B (n_517), .Y (n_62));
  NOR2BX1 g8040__1617(.AN (n_47), .B (n_387), .Y (n_48));
  XNOR2X1 g8039__2802(.A (refresh_counter[2]), .B (n_9), .Y (n_46));
  NAND2BXL g8047__5122(.AN (refresh_div[3]), .B (n_50), .Y (n_68));
  NOR2BX1 g8061__8246(.AN (n_135), .B (n_36), .Y (row[3]));
  NOR2BX1 g8051__7098(.AN (n_34), .B (n_134), .Y (row[4]));
  NOR2XL g8060__1881(.A (n_36), .B (n_134), .Y (row[5]));
  AND2XL g8053__5115(.A (n_34), .B (n_135), .Y (row[2]));
  NAND3XL g8049__7482(.A (n_32), .B (n_31), .C (n_30), .Y (n_33));
  NOR2BX1 g8050__4733(.AN (n_144), .B (n_36), .Y (row[1]));
  NOR2XL g8055__6161(.A (n_36), .B (n_143), .Y (row[7]));
  INVXL g8025(.A (n_989), .Y (n_27));
  OAI2BB1X1 g8048__9315(.A0N (n_21), .A1N (scan_pwm_counter[3]), .B0
       (brightness[3]), .Y (n_25));
  NAND2XL g8054__9945(.A (n_16), .B (n_23), .Y (n_24));
  NAND2XL g8056__2883(.A (n_21), .B (scan_pwm_counter[1]), .Y (n_22));
  OA21X1 g8063__2346(.A0 (scan_pwm_counter[1]), .A1
       (scan_pwm_counter[0]), .B0 (n_43), .Y (n_20));
  NOR2BX1 g8057__6417(.AN (n_16), .B (refresh_div[0]), .Y (n_50));
  NOR2BX1 g8052__5477(.AN (n_34), .B (n_143), .Y (row[6]));
  AND2XL g8059__2398(.A (n_34), .B (n_144), .Y (row[0]));
  AOI21XL g8065__5107(.A0 (refresh_div[0]), .A1 (refresh_div[1]), .B0
       (n_11), .Y (n_47));
  AOI21XL g8066__6260(.A0 (brightness[3]), .A1 (n_13), .B0
       (brightness[2]), .Y (n_54));
  INVXL g8067(.A (n_11), .Y (n_12));
  AND2X1 g8069__5526(.A (n_257), .B (brightness[0]), .Y (n_10));
  INVXL g8045(.A (n_8), .Y (n_9));
  NAND2XL g8086__6783(.A (n_282), .B (scan_pwm_counter[4]), .Y (n_36));
  NOR2X1 g8087__3680(.A (scan_pwm_counter[6]), .B (n_7), .Y (n_135));
  NAND2X1 g8088__1617(.A (scan_pwm_counter[6]), .B (n_7), .Y (n_134));
  NOR2X1 g8070__2802(.A (refresh_div[0]), .B (refresh_counter[0]), .Y
       (n_6));
  NAND2XL g8073__1705(.A (brightness[0]), .B (brightness[1]), .Y
       (n_21));
  NOR2XL g8082__8246(.A (refresh_div[1]), .B (refresh_div[2]), .Y
       (n_16));
  NOR2XL g8080__7098(.A (refresh_div[10]), .B (refresh_div[11]), .Y
       (n_31));
  NOR2XL g8081__6131(.A (refresh_div[8]), .B (refresh_div[9]), .Y
       (n_30));
  NOR2XL g8071__1881(.A (refresh_div[6]), .B (refresh_div[7]), .Y
       (n_32));
  NOR2XL g8076__5115(.A (scan_pwm_counter[5]), .B
       (scan_pwm_counter[6]), .Y (n_144));
  NAND2X1 g8078__7482(.A (refresh_counter[7]), .B (refresh_counter[4]),
       .Y (n_5));
  NAND2XL g8068__4733(.A (refresh_counter[9]), .B (n_396), .Y (n_4));
  NAND2X4 g8079__6161(.A (n_982), .B (n_374), .Y (n_3));
  NOR2XL g8072__9315(.A (refresh_div[0]), .B (refresh_div[1]), .Y
       (n_11));
  NOR2XL g8075__9945(.A (refresh_div[12]), .B (refresh_div[13]), .Y
       (n_23));
  NAND2X2 g8083__2883(.A (refresh_counter[1]), .B (refresh_counter[0]),
       .Y (n_8));
  NAND2X4 g8084__2346(.A (scan_pwm_counter[1]), .B
       (scan_pwm_counter[0]), .Y (n_43));
  NAND2XL g8077__1666(.A (scan_pwm_counter[6]), .B
       (scan_pwm_counter[5]), .Y (n_143));
  NOR2XL g8085__7410(.A (rst), .B (scan_pwm_counter[4]), .Y (n_34));
  INVX1 g8096(.A (scan_pwm_counter[5]), .Y (n_7));
  INVXL g8093(.A (scan_pwm_counter[3]), .Y (n_13));
  INVX1 g8095(.A (scan_pwm_counter[4]), .Y (n_71));
  INVX1 g8097(.A (scan_pwm_counter[0]), .Y (n_257));
  INVXL g8101(.A (rst), .Y (n_282));
  BUFX2 fopt8125(.A (n_247), .Y (n_372));
  INVXL fopt8127(.A (n_374), .Y (n_375));
  BUFX2 fopt2(.A (refresh_counter[5]), .Y (n_374));
  BUFX2 fopt8130(.A (refresh_counter[0]), .Y (n_381));
  INVX1 fopt8133(.A (refresh_counter[1]), .Y (n_387));
  BUFX2 fopt8134(.A (refresh_counter[12]), .Y (n_389));
  BUFX2 fopt8139(.A (refresh_counter[10]), .Y (n_396));
  XOR2XL g3(.A (n_387), .B (n_381), .Y (n_399));
  XOR2XL g8140(.A (refresh_counter[13]), .B (n_108), .Y (n_401));
  NOR2X1 g8142(.A (n_399), .B (n_803), .Y (n_407));
  NOR2X1 g7825__8168(.A (n_381), .B (n_803), .Y (n_431));
  NOR2X2 g8041__8252(.A (n_723), .B (n_43), .Y (n_517));
  NOR2X1 g7822__8267(.A (n_61), .B (n_803), .Y (n_542));
  NOR2X1 g7834__8287(.A (n_105), .B (n_803), .Y (n_563));
  AOI21X2 g7857__8299(.A0 (n_574), .A1 (n_1042), .B0 (n_576), .Y
       (n_577));
  OR3XL g7897__8300(.A (n_986), .B (n_1046), .C (n_1012), .Y (n_574));
  NAND2BX1 g7858__8302(.AN (n_235), .B (n_815), .Y (n_576));
  NOR2X2 g7847__8304(.A (n_247), .B (n_577), .Y (n_580));
  INVX2 g8359(.A (n_580), .Y (n_636));
  INVX1 g2(.A (n_811), .Y (n_673));
  NAND2X1 g123(.A (refresh_counter[9]), .B (n_1048), .Y (n_704));
  NOR2XL g84(.A (n_897), .B (refresh_counter[12]), .Y (n_707));
  AOI21X1 g81(.A0 (n_897), .A1 (refresh_counter[12]), .B0
       (refresh_counter[13]), .Y (n_709));
  NAND2X2 g53(.A (n_1015), .B (n_1049), .Y (n_716));
  NOR2BX1 g8413(.AN (n_242), .B (n_758), .Y (n_712));
  MX2XL g8418(.A (scan_pwm_counter[2]), .B (n_723), .S0 (n_43), .Y
       (n_724));
  NOR2XL g142(.A (scan_pwm_counter[0]), .B (n_1049), .Y (n_730));
  NAND2XL g23(.A (refresh_counter[13]), .B (refresh_counter[12]), .Y
       (n_733));
  OAI21X2 g151(.A0 (n_993), .A1 (n_737), .B0 (n_918), .Y (n_740));
  NOR2X1 g155(.A (n_901), .B (n_709), .Y (n_737));
  AOI2BB1X1 g32(.A0N (n_741), .A1N (refresh_counter[4]), .B0 (n_742),
       .Y (n_743));
  AOI21XL g33(.A0 (refresh_div[4]), .A1 (n_68), .B0 (n_65), .Y (n_741));
  NOR2BX1 g34_0(.AN (n_125), .B (refresh_counter[8]), .Y (n_742));
  NOR2BX1 g34(.AN (n_125), .B (refresh_counter[8]), .Y (n_744));
  NOR2X1 g21(.A (n_1046), .B (n_750), .Y (n_751));
  NOR2BX1 g8425(.AN (n_127), .B (refresh_counter[7]), .Y (n_750));
  NOR2X1 g8426(.A (n_750), .B (n_121), .Y (n_752));
  NAND2X1 g8428(.A (n_756), .B (n_751), .Y (n_757));
  AOI2BB1X1 g88(.A0N (n_754), .A1N (refresh_counter[6]), .B0 (n_755),
       .Y (n_756));
  XNOR2X1 g89(.A (n_83), .B (refresh_div[6]), .Y (n_754));
  NOR2X1 g90(.A (n_103), .B (refresh_counter[5]), .Y (n_755));
  AOI21X1 g8429(.A0 (n_756), .A1 (n_752), .B0 (n_137), .Y (n_758));
  AOI21XL g8430(.A0 (n_754), .A1 (refresh_counter[6]), .B0
       (refresh_counter[7]), .Y (n_759));
  NAND3X1 g8431(.A (n_754), .B (refresh_counter[7]), .C
       (refresh_counter[6]), .Y (n_760));
  BUFX2 g8432(.A (n_733), .Y (n_762));
  MXI2XL g112(.A (n_724), .B (n_723), .S0 (n_904), .Y (n_769));
  NOR2BX1 g50(.AN (n_771), .B (refresh_counter[3]), .Y (n_772));
  NAND2XL g51(.A (n_51), .B (n_68), .Y (n_771));
  NAND2BX1 g49(.AN (n_771), .B (refresh_counter[3]), .Y (n_774));
  BUFX2 g8449(.A (refresh_counter[3]), .Y (n_791));
  XNOR2X1 g7984__8453(.A (refresh_counter[4]), .B (n_795), .Y (n_796));
  BUFX2 g8454(.A (n_912), .Y (n_795));
  NAND2X2 g8003__8455(.A (refresh_counter[4]), .B (n_912), .Y (n_797));
  NOR2XL g7824__8460(.A (n_979), .B (n_401), .Y (n_802));
  BUFX3 g8461(.A (n_979), .Y (n_803));
  NOR2XL g7837__8465(.A (n_796), .B (n_979), .Y (n_807));
  NOR2XL g7823__8467(.A (n_979), .B (n_118), .Y (n_809));
  INVX1 g8469(.A (n_979), .Y (n_811));
  NOR3XL g8471(.A (n_707), .B (n_902), .C (n_1011), .Y (n_815));
  NOR2X1 g7821__8519(.A (n_80), .B (n_857), .Y (n_858));
  BUFX3 g8520(.A (n_979), .Y (n_857));
  NOR2X1 g7828__8521(.A (n_46), .B (n_859), .Y (n_860));
  BUFX2 g8522(.A (n_979), .Y (n_859));
  NOR2X1 g7832__8523(.A (n_93), .B (n_857), .Y (n_861));
  NOR2X1 g7831__8524(.A (n_988), .B (n_857), .Y (n_862));
  NOR2X1 g7830__8525(.A (n_98), .B (n_857), .Y (n_863));
  NOR2X2 g57(.A (n_898), .B (n_902), .Y (n_903));
  NOR2X1 g60(.A (n_897), .B (refresh_counter[12]), .Y (n_898));
  CLKXOR2X1 g62(.A (n_896), .B (refresh_div[12]), .Y (n_897));
  NAND2XL g64(.A (n_113), .B (n_31), .Y (n_896));
  NOR2BX1 g58(.AN (n_901), .B (refresh_counter[13]), .Y (n_902));
  NAND2XL g59(.A (n_899), .B (n_900), .Y (n_901));
  NAND2BXL g63(.AN (n_896), .B (n_23), .Y (n_899));
  OAI21XL g61(.A0 (refresh_div[12]), .A1 (n_896), .B0
       (refresh_div[13]), .Y (n_900));
  NOR2XL g8561(.A (n_979), .B (n_112), .Y (n_906));
  NOR2X4 g26(.A (n_636), .B (n_716), .Y (n_904));
  NOR3X4 g31(.A (n_908), .B (n_911), .C (n_913), .Y (n_914));
  INVX2 g38(.A (n_907), .Y (n_908));
  NOR2X4 g39(.A (n_5), .B (n_3), .Y (n_907));
  INVX1 g8562(.A (n_910), .Y (n_911));
  NOR2BX1 g8563(.AN (n_991), .B (n_4), .Y (n_910));
  INVX2 g36(.A (n_912), .Y (n_913));
  CLKAND2X3 g37(.A (n_791), .B (n_989), .Y (n_912));
  NAND2X4 g8564(.A (n_907), .B (n_912), .Y (n_915));
  NOR2X2 g19(.A (n_916), .B (n_917), .Y (n_918));
  NOR2BX1 g20(.AN (n_204), .B (refresh_counter[14]), .Y (n_916));
  NOR2X1 g8565(.A (n_230), .B (refresh_counter[15]), .Y (n_917));
  NAND2X2 g8583(.A (n_918), .B (n_1013), .Y (n_933));
  NOR2X1 g47(.A (n_233), .B (n_757), .Y (n_936));
  NOR2X1 g8618(.A (n_673), .B (n_997), .Y (n_974));
  NAND2BX1 g8620(.AN (n_990), .B (n_1048), .Y (n_966));
  INVX1 g4(.A (refresh_counter[11]), .Y (n_968));
  AOI211XL g8622(.A0 (n_975), .A1 (n_976), .B0 (n_978), .C0 (n_979), .Y
       (n_980));
  INVX1 g52(.A (refresh_counter[14]), .Y (n_975));
  NAND2BX1 g8623(.AN (n_762), .B (n_914), .Y (n_976));
  NOR2X1 g8624(.A (n_977), .B (n_81), .Y (n_978));
  OR2XL g8625(.A (n_975), .B (n_762), .Y (n_977));
  CLKINVX6 g8626(.A (n_904), .Y (n_979));
  BUFX3 fopt8628(.A (refresh_counter[6]), .Y (n_982));
  DFFRX1 \scan_pwm_counter_reg[2] (.RN (n_282), .CK (clk), .D (n_769),
       .Q (scan_pwm_counter[2]), .QN (n_723));
  NAND2BX1 g8632(.AN (n_125), .B (refresh_counter[8]), .Y (n_986));
  MXI2X1 g8633(.A (n_135), .B (scan_pwm_counter[6]), .S0 (n_76), .Y
       (n_987));
  XOR2XL g8634(.A (refresh_counter[8]), .B (n_915), .Y (n_988));
  NOR2BX1 g8635(.AN (refresh_counter[2]), .B (n_8), .Y (n_989));
  NAND2XL g8636(.A (n_396), .B (refresh_counter[9]), .Y (n_990));
  NOR2BX1 g8637(.AN (refresh_counter[8]), .B (n_968), .Y (n_991));
  NOR2BX1 g8638(.AN (n_577), .B (scan_pwm_counter[0]), .Y (n_992));
  NOR2BX1 g8639(.AN (n_897), .B (n_733), .Y (n_993));
  OR2XL g8641(.A (n_966), .B (n_968), .Y (n_995));
  AOI2BB1XL g8642(.A0N (refresh_counter[15]), .A1N (n_978), .B0
       (n_979), .Y (n_996));
  OAI2BB1X1 g8643(.A0N (n_966), .A1N (n_968), .B0 (n_995), .Y (n_997));
  NAND2BX2 g102(.AN (n_998), .B (n_999), .Y (n_1000));
  AOI21X1 g103(.A0 (n_774), .A1 (n_58), .B0 (n_772), .Y (n_998));
  OAI21X2 g104(.A0 (n_48), .A1 (n_53), .B0 (n_1050), .Y (n_999));
  NAND3X1 g78(.A (n_1002), .B (n_1051), .C (n_1004), .Y (n_1005));
  NAND2X1 g80(.A (n_256), .B (n_1047), .Y (n_1002));
  AOI21X1 g79(.A0 (n_257), .A1 (n_1014), .B0 (n_730), .Y (n_1004));
  INVXL g8646(.A (n_896), .Y (n_1006));
  NOR2X1 g8649(.A (n_1011), .B (n_1012), .Y (n_1013));
  NOR2X1 g8650(.A (n_1038), .B (refresh_counter[11]), .Y (n_1011));
  NOR2BX1 g22(.AN (n_147), .B (refresh_counter[10]), .Y (n_1012));
  INVX1 fopt(.A (n_1015), .Y (n_1014));
  INVX2 fopt8651(.A (n_712), .Y (n_1015));
  AOI21XL g8676(.A0 (refresh_div[11]), .A1 (n_130), .B0 (n_1006), .Y
       (n_1038));
  AOI2BB1X2 g7887__8677(.A0N (n_136), .A1N (n_1012), .B0 (n_1041), .Y
       (n_1042));
  NAND2X2 g1(.A (n_1045), .B (n_1040), .Y (n_1041));
  NAND2X1 g8679(.A (n_1038), .B (refresh_counter[11]), .Y (n_1040));
  NAND2BX1 g8682(.AN (n_147), .B (refresh_counter[10]), .Y (n_1045));
  NOR2X2 g8683(.A (n_132), .B (refresh_counter[9]), .Y (n_1046));
  NOR3BX1 g8684(.AN (n_1049), .B (n_257), .C (n_577), .Y (n_1047));
  NOR2BX4 g8685(.AN (refresh_counter[8]), .B (n_915), .Y (n_1048));
  NAND3BX2 g8686(.AN (n_933), .B (n_1000), .C (n_936), .Y (n_1049));
  AOI2BB1X1 g8687(.A0N (n_57), .A1N (refresh_counter[2]), .B0 (n_772),
       .Y (n_1050));
  AOI21X1 g8688(.A0 (n_257), .A1 (n_372), .B0 (n_992), .Y (n_1051));
endmodule

