
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  7 2026 13:56:53 IST (Sep  7 2026 08:26:53 UTC)

// Verification Directory fv/dut 

module dut(clk, rst, display_data, brightness, row, col);
  input clk, rst;
  input [63:0] display_data;
  input [3:0] brightness;
  output [7:0] row, col;
  wire clk, rst;
  wire [63:0] display_data;
  wire [3:0] brightness;
  wire [7:0] row, col;
  wire [3:0] pwm_count;
  wire [2:0] scan_count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_16, n_18;
  wire n_19, n_21, n_23, n_24, n_25, n_26, n_29, n_30;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69;
  NAND4XL g2362__2398(.A (n_33), .B (n_46), .C (n_56), .D (n_58), .Y
       (col[5]));
  NAND4XL g2360__5107(.A (n_30), .B (n_39), .C (n_49), .D (n_52), .Y
       (col[6]));
  NAND4XL g2361__6260(.A (n_40), .B (n_44), .C (n_53), .D (n_62), .Y
       (col[7]));
  NAND4XL g2363__4319(.A (n_32), .B (n_42), .C (n_68), .D (n_51), .Y
       (col[4]));
  NAND4XL g2364__8428(.A (n_34), .B (n_41), .C (n_54), .D (n_61), .Y
       (col[1]));
  NAND4XL g2365__5526(.A (n_36), .B (n_45), .C (n_66), .D (n_60), .Y
       (col[2]));
  NAND4XL g2359__6783(.A (n_37), .B (n_43), .C (n_55), .D (n_64), .Y
       (col[3]));
  NAND4XL g2366__3680(.A (n_29), .B (n_35), .C (n_50), .D (n_69), .Y
       (col[0]));
  AOI22XL g2387__1617(.A0 (display_data[0]), .A1 (n_67), .B0
       (display_data[48]), .B1 (n_63), .Y (n_69));
  AOI22XL g2368__2802(.A0 (display_data[4]), .A1 (n_67), .B0
       (display_data[28]), .B1 (n_65), .Y (n_68));
  AOI22XL g2375__1705(.A0 (display_data[2]), .A1 (n_67), .B0
       (display_data[26]), .B1 (n_65), .Y (n_66));
  AOI22XL g2369__5122(.A0 (display_data[51]), .A1 (n_63), .B0
       (display_data[59]), .B1 (n_59), .Y (n_64));
  AOI22XL g2385__8246(.A0 (display_data[23]), .A1 (n_57), .B0
       (display_data[55]), .B1 (n_63), .Y (n_62));
  AOI22XL g2377__7098(.A0 (display_data[49]), .A1 (n_63), .B0
       (display_data[25]), .B1 (n_65), .Y (n_61));
  AOI22XL g2367__6131(.A0 (display_data[50]), .A1 (n_63), .B0
       (display_data[58]), .B1 (n_59), .Y (n_60));
  AOI22XL g2382__1881(.A0 (display_data[21]), .A1 (n_57), .B0
       (display_data[53]), .B1 (n_63), .Y (n_58));
  AOI22XL g2378__5115(.A0 (display_data[5]), .A1 (n_67), .B0
       (display_data[29]), .B1 (n_65), .Y (n_56));
  AOI22XL g2370__7482(.A0 (display_data[3]), .A1 (n_67), .B0
       (display_data[27]), .B1 (n_65), .Y (n_55));
  AOI22XL g2379__4733(.A0 (display_data[1]), .A1 (n_67), .B0
       (display_data[57]), .B1 (n_59), .Y (n_54));
  AOI22XL g2381__6161(.A0 (display_data[7]), .A1 (n_67), .B0
       (display_data[63]), .B1 (n_59), .Y (n_53));
  AOI22XL g2374__9315(.A0 (display_data[6]), .A1 (n_67), .B0
       (display_data[54]), .B1 (n_63), .Y (n_52));
  AOI22XL g2388__9945(.A0 (display_data[52]), .A1 (n_63), .B0
       (display_data[60]), .B1 (n_59), .Y (n_51));
  AOI22XL g2384__2883(.A0 (display_data[32]), .A1 (n_48), .B0
       (display_data[8]), .B1 (n_47), .Y (n_50));
  AOI22XL g2371__2346(.A0 (display_data[38]), .A1 (n_48), .B0
       (display_data[14]), .B1 (n_47), .Y (n_49));
  AOI22XL g2383__1666(.A0 (display_data[37]), .A1 (n_48), .B0
       (display_data[13]), .B1 (n_47), .Y (n_46));
  AOI22XL g2376__7410(.A0 (display_data[34]), .A1 (n_48), .B0
       (display_data[10]), .B1 (n_47), .Y (n_45));
  AOI22XL g2373__6417(.A0 (display_data[39]), .A1 (n_48), .B0
       (display_data[15]), .B1 (n_47), .Y (n_44));
  AOI22XL g2372__5477(.A0 (display_data[35]), .A1 (n_48), .B0
       (display_data[11]), .B1 (n_47), .Y (n_43));
  AOI22XL g2386__2398(.A0 (display_data[36]), .A1 (n_48), .B0
       (display_data[12]), .B1 (n_47), .Y (n_42));
  AOI22XL g2380__5107(.A0 (display_data[33]), .A1 (n_48), .B0
       (display_data[9]), .B1 (n_47), .Y (n_41));
  AOI22XL g2392__6260(.A0 (display_data[47]), .A1 (n_38), .B0
       (display_data[31]), .B1 (n_65), .Y (n_40));
  AOI22XL g2391__4319(.A0 (display_data[22]), .A1 (n_57), .B0
       (display_data[46]), .B1 (n_38), .Y (n_39));
  AOI22XL g2390__8428(.A0 (display_data[19]), .A1 (n_57), .B0
       (display_data[43]), .B1 (n_38), .Y (n_37));
  AOI22XL g2393__5526(.A0 (display_data[18]), .A1 (n_57), .B0
       (display_data[42]), .B1 (n_38), .Y (n_36));
  AOI22XL g2397__6783(.A0 (display_data[16]), .A1 (n_57), .B0
       (display_data[40]), .B1 (n_38), .Y (n_35));
  AOI22XL g2396__3680(.A0 (display_data[17]), .A1 (n_57), .B0
       (display_data[41]), .B1 (n_38), .Y (n_34));
  AOI22XL g2395__1617(.A0 (display_data[45]), .A1 (n_38), .B0
       (display_data[61]), .B1 (n_59), .Y (n_33));
  AOI22XL g2398__2802(.A0 (display_data[20]), .A1 (n_57), .B0
       (display_data[44]), .B1 (n_38), .Y (n_32));
  AND2X1 g2401__1705(.A (row[6]), .B (n_24), .Y (n_63));
  AOI21XL g2402__5122(.A0 (n_12), .A1 (n_26), .B0 (n_7), .Y (n_67));
  AOI22XL g2389__8246(.A0 (display_data[30]), .A1 (n_65), .B0
       (display_data[62]), .B1 (n_59), .Y (n_30));
  AOI22XL g2394__7098(.A0 (display_data[24]), .A1 (n_65), .B0
       (display_data[56]), .B1 (n_59), .Y (n_29));
  DFFQXL \pwm_count_reg[3] (.CK (clk), .D (n_25), .Q (pwm_count[3]));
  OA21X1 g2403__6131(.A0 (n_23), .A1 (n_21), .B0 (row[4]), .Y (n_48));
  DFFHQX1 \pwm_count_reg[2] (.CK (clk), .D (n_19), .Q (scan_count[2]));
  NOR2BX1 g2406__1881(.AN (row[1]), .B (n_26), .Y (n_47));
  NOR2X1 g2407__5115(.A (rst), .B (n_16), .Y (n_25));
  OAI2BB1X1 g2408__7482(.A0N (brightness[1]), .A1N (n_23), .B0 (n_14),
       .Y (n_24));
  AND2X1 g2409__4733(.A (row[5]), .B (n_21), .Y (n_38));
  OA21X1 g2410__6161(.A0 (n_13), .A1 (n_18), .B0 (row[2]), .Y (n_57));
  NOR2X1 g2404__9315(.A (rst), .B (n_11), .Y (n_19));
  AOI21XL g2411__9945(.A0 (brightness[1]), .A1 (n_2), .B0 (n_18), .Y
       (n_26));
  AND2X1 g2405__2883(.A (row[3]), .B (n_18), .Y (n_65));
  XNOR2X1 g2413__2346(.A (pwm_count[3]), .B (row[7]), .Y (n_16));
  OAI2BB1X1 g2414__1666(.A0N (brightness[1]), .A1N (n_10), .B0 (n_14),
       .Y (n_21));
  DFFHQX1 \scan_count_reg[1] (.CK (clk), .D (n_9), .Q (scan_count[1]));
  NOR2BX1 g2415__7410(.AN (brightness[1]), .B (n_12), .Y (n_13));
  NOR2BX1 g2416__6417(.AN (brightness[2]), .B (n_12), .Y (n_23));
  AOI21X1 g2419__5477(.A0 (scan_count[2]), .A1 (n_3), .B0 (row[3]), .Y
       (n_11));
  NAND2BXL g2417__2398(.AN (n_10), .B (n_14), .Y (n_18));
  NOR2BX1 g2420__5107(.AN (row[7]), .B (n_14), .Y (n_59));
  AOI21XL g2418__6260(.A0 (n_1), .A1 (n_4), .B0 (rst), .Y (n_9));
  INVXL g2421(.A (n_7), .Y (row[0]));
  AND2X1 g2423__4319(.A (n_6), .B (scan_count[2]), .Y (row[4]));
  NAND2XL g2422__8428(.A (n_5), .B (n_6), .Y (n_7));
  NOR2XL g2427__5526(.A (n_5), .B (n_4), .Y (row[5]));
  NOR2X1 g2425__6783(.A (n_5), .B (n_3), .Y (row[7]));
  NAND2XL g2424__3680(.A (brightness[0]), .B (n_2), .Y (n_12));
  NOR2XL g2428__1617(.A (scan_count[2]), .B (n_1), .Y (row[2]));
  AND2X1 g2429__2802(.A (n_2), .B (brightness[2]), .Y (n_10));
  NOR2XL g2430__1705(.A (n_5), .B (n_1), .Y (row[6]));
  NOR2XL g2431__5122(.A (scan_count[2]), .B (n_4), .Y (row[1]));
  NOR2X1 g2432__8246(.A (scan_count[2]), .B (n_3), .Y (row[3]));
  DFFHQX1 \scan_count_reg[0] (.CK (clk), .D (n_0), .Q (scan_count[0]));
  NOR2X1 g2433__7098(.A (rst), .B (scan_count[0]), .Y (n_0));
  NOR2XL g2434__6131(.A (scan_count[0]), .B (scan_count[1]), .Y (n_6));
  NAND2BXL g2439__1881(.AN (pwm_count[3]), .B (brightness[3]), .Y
       (n_14));
  NAND2BX1 g2438__5115(.AN (scan_count[0]), .B (scan_count[1]), .Y
       (n_1));
  NAND2BXL g2437__7482(.AN (brightness[3]), .B (pwm_count[3]), .Y
       (n_2));
  NAND2BX1 g2435__4733(.AN (scan_count[1]), .B (scan_count[0]), .Y
       (n_4));
  NAND2X1 g2436__6161(.A (scan_count[1]), .B (scan_count[0]), .Y (n_3));
  INVX1 g2440(.A (scan_count[2]), .Y (n_5));
endmodule

